### ISSUE TITLE
Window Decorations settings button won't work

### ISSUE THREAD

**Issue by scarf005** [paulmcauley/classik#20]
### summary
![image](https://user-images.githubusercontent.com/54838975/159267465-e04879b3-d9b7-409f-a6b7-07197e2180e1.png)
![image](https://user-images.githubusercontent.com/54838975/159267510-f44add43-519b-42c9-94de-417291c8f651.png)
program style settings button work,
![image](https://user-images.githubusercontent.com/54838975/159267390-9066b875-fcd0-4185-81fd-098ab88fb42c.png)
however window decorations button does not.

### downloaded package
[debian->grab binary packages directly-> classik_3.0.breeze5.23.80-1_amd64.deb](https://software.opensuse.org//download.html?project=home%3Apaul4us&package=classik)

### system information
```yaml
OS: Kubuntu 21.10 x86_64
kde plasma version: 5.22.5
kde framwork version: 5.86.0
qt version: 5.15.2
kernel version: 5.13.0-34-generic
graphic platform: X11
```
